repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [ toml ]

  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 0.2.0
    hooks:
      - id: sync_with_poetry

  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [ "--no-update" ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.152
    hooks:
      - id: ruff
