repos:
  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        additional_dependencies: [
          "flake8-bugbear", "flake8-comprehensions", "flake8-import-order",
          "flake8-logging-format", "flake8-use-pathlib"
        ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: pretty-format-json
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      - id: mypy
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.6'
    hooks:
      - id: vulture

  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: sh -c "./src/manage.py makemigrations --check --dry-run"
        files: "models\\.py$"
        stages: [ commit ]
