global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

rule_files:
  - "django_rules.yml"

scrape_configs:
  - job_name: "django"
    static_configs:
    - targets: ["backend:8000"]
  - job_name: postgres-exporter
    static_configs:
      - targets: [ "postgres-exporter:9187" ]
