# Generated by Django 4.1.3 on 2022-11-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_index_for_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='image', upload_to='', verbose_name='image of the post'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='articletagitem',
            unique_together={('tag', 'post')},
        ),
    ]
