# Generated by Django 4.1.3 on 2022-12-23 15:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_article_constraints"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="articlelike",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="article",
            name="likes",
            field=models.ManyToManyField(
                related_name="articles", to="blog.articlelike"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="articles",
                through="blog.ArticleTagItem",
                to="blog.articletag",
            ),
        ),
        migrations.RemoveField(
            model_name="articlelike",
            name="article",
        ),
    ]
